### ISSUE TITLE
Highlight group doesn't change FG color

### ISSUE THREAD

**Issue by cd-a** [ruanyl/coc-coverage#3]
Thanks for this plugin!

Using the highlight group I can change the background color, however the icon color can't be changed with the FG color.

**Comment by ruanyl** [comment]
Thanks for reporting. Could you make a screenshot and share the configuration?

And PR is welcome :)

**Comment by cd-a** [comment]
This is the configuration that I use:
```
" Highlight group for coverage
highlight UncoveredLine guifg=#ff0000 guibg=#ff0000
```

As you can see, the background gets adjusted to red, but the icon never changes:
![Screenshot 2021-04-25 at 09 45 08](https://user-images.githubusercontent.com/75008413/115985222-18dc1800-a5ab-11eb-8b0e-28437c55da91.png)

For now I use it with 
```
guibg=NONE
```
And it looks good, but just not able to change the icon color.

As I understand it, it's happening because at https://github.com/ruanyl/coc-coverage/blob/master/src/index.ts#L81 you define the guifg color statically, but not the bg color. Which leaves the user to choose the bg color, but the fg is hardcoded. Is that correct?

**Comment by ruanyl** [comment]
Right, the intention was to give it an initial sign-color when it's not set by the user. But clearly, this will overwrite the user's settings.

I guess I'm ganna remove that line and leave it completely to the user to choose the colors. 

And If you have a fix to it already, PR is very welcome :)

**Comment by cd-a** [comment]
Thanks for the fix, appreciate it!
